"""
Configuration module for ETL pipeline
"""

from src.config.config import (
    GCP_CREDENTIALS_PATH,
    GCP_PROJECT_ID,
    BIGQUERY_DATASET,
    BIGQUERY_TABLE,
    MONGO_COLLECTION,
    MONGO_DATABASE,
    MONGO_URI,
    ETL_START_YEAR,
    ETL_END_YEAR,
    ETL_LIMIT,
    BQ_TABLE_CENSO_IES,
    BQ_TABLE_CENSO_CURSO,
    BQ_TABLE_SISU_MICRODADOS,
    BQ_TABLE_CENSO_DICIONARIO,
    MONGO_COLLECTION_GOLD_COURSE,
    MONGO_COLLECTION_SISU_AGGREGATED,
)

__all__ = [
    "GCP_PROJECT_ID",
    "GCP_CREDENTIALS_PATH",
    "MONGO_URI",
    "MONGO_DATABASE",
    "MONGO_COLLECTION",
    "BIGQUERY_DATASET",
    "BIGQUERY_TABLE",
    "ETL_START_YEAR",
    "ETL_END_YEAR",
    "ETL_LIMIT",
    "BQ_TABLE_CENSO_IES",
    "BQ_TABLE_CENSO_CURSO",
    "BQ_TABLE_SISU_MICRODADOS",
    "BQ_TABLE_CENSO_DICIONARIO",
    "MONGO_COLLECTION_GOLD_COURSE",
    "MONGO_COLLECTION_SISU_AGGREGATED",
]
